name: the_movie_db_flutter
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^2.5.0
  convex_bottom_bar: ^3.0.0
  cupertino_icons: ^1.0.2
  device_simulator: ^0.9.6
  dio: ^3.0.10
  equatable: ^2.0.0
  flutter_bloc: ^7.0.0
  flutter_i18n: ^0.22.3
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.5+1
  flutter_svg: ^0.19.2
  google_fonts: ^2.0.0
  http: ^0.13.1
  hydrated_bloc: ^7.0.0
  path_provider: ^2.0.1

dependency_overrides:
  http_parser: 4.0.0
  xml: 5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path_android: assets/icons/app_icon.png
  ios: true
  image_path_ios: assets/icons/app_icon.png


flutter_native_splash:
  image: assets/icons/app_icon.png
  color: "#000000"

flutter:
  assets:
    - assets/flutter_i18n/
    - assets/icons/

  uses-material-design: true

