name: the_movie_db_flutter
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.0.0
  convex_bottom_bar: ^3.0.0
  cupertino_icons: ^1.0.3
  device_simulator: ^0.9.6
  dio: ^4.0.0
  equatable: ^2.0.3
  flutter_bloc: ^7.0.1
  flutter_i18n: ^0.22.4
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.2.0
  flutter_svg: ^0.22.0
  flutter_web_browser: ^0.14.0
  google_fonts: ^2.1.0
  http: ^0.13.3
  hydrated_bloc: ^7.0.1
  path_provider: ^2.0.2
  url_launcher: ^6.0.3

dependency_overrides:
  args: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path_android: assets/icons/app_icon.png
  ios: true
  image_path_ios: assets/icons/app_icon.png


flutter_native_splash:
  image: assets/icons/app_icon.png
  color: "#000000"

flutter:
  assets:
    - assets/flutter_i18n/
    - assets/icons/

  uses-material-design: true

